version: 2

formats:
   - epub
   - pdf

build:
  image: latest

python:
  version: 3.8
  install:
     - method: pip
       path: .
  system_packages: true

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
